### ISSUE TITLE
Improvements Checklist

### ISSUE THREAD

**Issue by pi0** [nuxt/modules#200]
Perf:

- [ ] ~~Fix CSS flashing issues with nitro~~ (using vite now. should find webpack4 issue later)
- [ ] ~~Fix image module support with nitro~~ (removed image module)
- [ ] ~~Cache github requests (cachify)~~ (moved to api.nuxtjs org)
- [ ] ~~Server-side search and filtering~~ (nor priority)

Design:

- [x] Support dark mode 
- [x] Fix windicss migration regressions
- [x] Improve version compatibility badges design
- [x] Improve version switch design

Functionality:

- [x] Allow toggling between v2, bridge, and v3 filters

Maintenance:

- [x] Switch back to vercel
- [ ] Update compatibility support of modules in `unknown` status
- [x] Fix npm auto-publish token
- [ ] Finalize open PRs to reject and merge
- [ ] Check open request issues
- [x] Build with the latest content instead of using npmjs

Ecosystem:

- [x] Redirect from https://nuxtjs.org/modules/ to https://modules.nuxtjs.org
- [ ] Add links to https://v3.nuxtjs.org/ to https://modules.nuxtjs.org (https://github.com/nuxt/framework/issues/1691)
- [ ] Update link to module creation docs 
- [ ] Module compatibility check when using bridge and nuxt 3 to warn

**Comment by productdevbook** [comment]
Design: working https://github.com/nuxt/modules/pull/204

**Comment by pi0** [comment]
The majority of issues were solved. Huge thanks to @productdevbook and @antfu made this possible 💚  Let's split next steps into smaller issues.
